apiVersion: v1
kind: Service
metadata:
  name: servicio-examen-1
  labels:
    name: servicio-examen-1
    app: caas-kube-examen-1
spec:
  type: NodePort
  selector:
    app: caas-kube-examen-1
  ports:
    - protocol: TCP
      port: 5500
      nodePort: 30004